Fix build w/ xapian-1.3
Caused by upstream change:
http://code.metager.de/source/xref/xapian/xapian-core/ChangeLog#3875

In file included from lib/indexeditems.cpp:28:0:
/usr/include/xapian-1.3/xapian/error.h:27:3: error:
 # error "Never use <xapian/error.h> directly; include <xapian.h> instead."

This change is backwards compatible with xapian-1.2

REVIEW: 128264